# Generated by Django 4.2.30 on 2026-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Country', max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
