# Generated by Django 4.2.30 on 2026-05-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
