# Generated by Django 4.2.30 on 2026-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
