# Generated by Django 4.2.30 on 2026-05-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_allow_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='allow_comments',
        ),
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
