# Generated by Django 4.2.30 on 2026-05-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_page_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.series')),
            ],
            options={
                'verbose_name': 'Series/Post',
                'ordering': ['order'],
            },
        ),
    ]
