# Generated by Django 4.2.30 on 2026-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_allow_comments_post_allow_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.CharField(blank=True, help_text='Keyword', max_length=7, null=True, unique=True),
        ),
    ]
