# Generated by Django 4.2.30 on 2026-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_alter_series_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keyword',
            field=models.CharField(blank=True, choices=[('home', 'Home Page'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy'), ('cookie', 'Cookie Policy')], help_text='Keyword', max_length=7, null=True, unique=True),
        ),
    ]
