# Generated by Django 4.2.30 on 2026-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keyword',
        ),
        migrations.AddField(
            model_name='page',
            name='keyword',
            field=models.CharField(blank=True, choices=[('home', 'Home Page'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy'), ('cookie', 'Cookie Policy')], help_text='Keyword', max_length=7, null=True, unique=True),
        ),
    ]
