# Generated by Django 4.2.30 on 2026-06-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='keyword',
            field=models.CharField(blank=True, choices=[('home', 'Home Page'), ('hero', 'Hero'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy'), ('cookie', 'Cookie Policy')], help_text='Keyword', max_length=7, null=True, unique=True),
        ),
    ]
