# Generated by Django 4.2.30 on 2026-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_page_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Image alt text', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='image_title',
            field=models.CharField(blank=True, help_text='Image title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Image alt text', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_title',
            field=models.CharField(blank=True, help_text='Image title', max_length=100, null=True),
        ),
    ]
