# Generated by Django 4.2.30 on 2026-05-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_page_image_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.series')),
            ],
        ),
    ]
