# Generated by Django 4.2.30 on 2026-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_page_image_alt_text_page_image_title_page_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='priority',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
