# Generated by Django 4.2.30 on 2026-07-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_series_priority_series_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='main_menu',
            field=models.PositiveBigIntegerField(blank=True, default=0, help_text='Non-zero to show on main menu', null=True),
        ),
    ]
