# Generated by Django 4.2.30 on 2026-07-21 20:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_page_main_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Series description', null=True),
        ),
    ]
