# Generated by Django 4.2.30 on 2026-07-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_series_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seriespost',
            constraint=models.UniqueConstraint(fields=('series', 'post'), name='series_post'),
        ),
    ]
